### ISSUE TITLE
Searching by tag showing first tag in list, not found tag

### ISSUE THREAD

**Issue by balucha** [pluginsGLPI/tag#14]
computer tags
![tag1](https://cloud.githubusercontent.com/assets/13922307/13234701/529f4e4e-d9ba-11e5-993a-2384d9c6aa11.png)

searching result
![tag2](https://cloud.githubusercontent.com/assets/13922307/13234702/52c284f4-d9ba-11e5-9886-82b069f93ed8.png)

**Comment by Manu1400** [comment]
What version of plugin Tag and GLPI do you used ?

**Comment by balucha** [comment]
Tag version 1.2,  GLPI version 0.85.5

**Comment by Manu1400** [comment]
FYI : Already fixed in the last version of Tag plugin with GLPI 0.90 : #5

**Comment by balucha** [comment]
Ok, but this version work s only with GLPI 0.90. Could you create version for 0.85.5

**Comment by trasher** [comment]
We do not plan to support 0.85x versions. You can either open a PR making plugin backward compatible; or write a line to contact@teclib.com.
