### ISSUE TITLE
Associated items tab empty

### ISSUE THREAD

**Issue by shoothub** [pluginsGLPI/tag#159]
**Describe the bug**
Items associated with tag is not linked, and the tab "Associated items" is empty. So it's not possible to list all associated items with tag.

**To Reproduce**
1. Associate tag with item
2. Go to 'Setup - Dropdowns - Tags'
3. Edit tag and click on tab "Associated items"'
3. List of associated items is empty. I should contain all associated items to the tag.
4. When I open Historical tab, a can see information about link to item: Add a link with an item:, but tab "Associated items" is still empty

**Expected behavior**
Get all associated items to tag in tab "Associated items" in section 'Setup - Dropdowns - Tags - tag', as described in the bottom of the manual:
https://glpi-plugins.readthedocs.io/en/latest/tag/index.html#usage

**Screenshots**
![image](https://github.com/pluginsGLPI/tag/assets/28008456/0a087c5e-fece-4dcf-b087-88d448f6fd9d)
![image](https://github.com/pluginsGLPI/tag/assets/28008456/d70c615d-9ce4-4e06-9573-8ffe9eeb6208)
![image](https://github.com/pluginsGLPI/tag/assets/28008456/bec4fec2-8eab-4fce-ad3f-be5b3790457d)

**GLPI / Plugins (please complete the following information):**
- GLPI version: 10.0.10
    - PHP 8.1.23 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysql, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
    - MariaDB Server 10.3.32
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page):
   - escalade             Name: Escalation                     Version: 2.9.2      State: Installed / not activated               
		Install Method: Manual
   - oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Installed / not activated               
		Install Method: Manual
   -	tag                  Name: Tag management                 Version: 2.11.6     State: Enabled                                 
		Install Method: Manual
   -	news                 Name: News                    Version: 1.12.1     State: Installed / not activated               
		Install Method: Manual

**Desktop (please complete the following information):**
 - OS: [Debian GNU/Linux 12 Bookworm]
 - Browser [Firefox]
 - Version [115.4.0esr (64-bit)]

**Additional context**

**Comment by stonebuzz** [comment]
I do not reproduce ATM

![image](https://github.com/pluginsGLPI/tag/assets/7335054/a8f5ee74-f737-4022-ab07-1cdc7f642888)

Can you enable debug mode and retry to see if error are displayed

**Comment by stonebuzz** [comment]
Ok it's fix from ```main``` (not relesed yet)

There is a patch, can you try it?

```patch
diff --git a/inc/tagitem.class.php b/inc/tagitem.class.php
index a82c969..97599a6 100644
--- a/inc/tagitem.class.php
+++ b/inc/tagitem.class.php
@@ -116,7 +116,7 @@ class PluginTagTagItem extends CommonDBRelation {
          'FROM'   => $table,
          'WHERE'  => ['plugin_tag_tags_id' => $instID]
       ]);
-      $result = [];
+      $result2 = [];
       foreach ($it2 as $data) {
          $result2[] = $data;
       }
```

**Comment by trasher** [comment]
Seems already fixed for next release; I close.
