### ISSUE TITLE
error during install of 0.90-1.2

### ISSUE THREAD

**Issue by Stoatwblr** [pluginsGLPI/tag#18]
2016-07-06 21:39:56 [11@msslyz.mssl.ucl.ac.uk]
  *** MySQL query error:
  SQL: CREATE TABLE IF NOT EXISTS `glpi_plugin_tag_tagitems` (
                `id` INT(11) NOT NULL AUTO_INCREMENT,
                `plugin_tag_tags_id` INT(11) NOT NULL DEFAULT \'0\',
                `items_id` INT(11) NOT NULL DEFAULT \'1\',
                `itemtype` VARCHAR(255) NOT NULL DEFAULT \'\' COLLATE \'utf8_unicode_ci\',
                PRIMARY KEY (`id`),
                UNIQUE INDEX `unicity` (`itemtype`, `items_id`, `plugin_tag_tags_id`),
            )
            COLLATE=\'utf8_unicode_ci\'
            ENGINE=MyISAM
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
            COLLATE='utf8_unicode_ci'
            ENGINE=MyISAM' at line 8
  Backtrace :
  plugins/tag/inc/tagitem.class.php:35
  plugins/tag/hook.php:205                           PluginTagTagItem::install()
  inc/plugin.class.php:643                           plugin_tag_install()
  :                                                  Plugin->install()
  front/plugin.form.php:49                           call_user_func()

**Comment by Stoatwblr** [comment]
./inc/tagitem.class.php - line 33

           COLLATE='utf8_unicode_ci'
       ^^^^^^^^^^^^^^^^ missing comma (,) at end of line
            ENGINE=MyISAM";

 ./inc/tag.class.php - line 113
                    KEY `name` (`name`)
^^^^^^^^^^^^^^^  missing comma (,)  at end of line
                     ) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";

**Comment by trasher** [comment]
Looks like this one has already been fixed in 42ed797

**Comment by Stoatwblr** [comment]
Confirmed
