### ISSUE TITLE
Gérer les tags dans les actions massives des objets

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/tag#2]
Hello,

Dans la liste des objets sur lesquels on peut appliquer un TAG (exemple les tickets), il faudrait : 
- pouvoir ajouter un ou des tag
- pouvoir retirer un ou des tag

++

**Comment by Manu1400** [comment]
Il faudrait impérativement limiter ça à certains objets GLPI (Tickets, etc) et d'éviter ainsi certains objets GLPI et surtout les plugins.

**Comment by orthagh** [comment]
adding tag is done in #26

**Comment by orthagh** [comment]
Done in 2.0.0
