### ISSUE TITLE
 Tags in the tag field are no longer searched for

### ISSUE THREAD

**Issue by geppauso** [pluginsGLPI/tag#206]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0.16

### Plugin version

2.12.0

### Bug description

Tags in the tag field are no longer searched for. This warning appears in debug mode:
**_SQL Error "1054": Unknown column 'is_active' in 'where clause' in query "SELECT * FROM `glpi_plugin_tag_tags` WHERE `is_active` = '1' AND ((`type_menu` IS NULL) OR (`type_menu` = '') OR (`type_menu` = '0') OR (`type_menu` LIKE '%"PluginMfaConfig"%')) ORDER BY `name`"_**

**Comment by merlin-tc** [comment]
Having the same problem since the last update to version 2.12.

**Comment by Rom1-B** [comment]
Hello @geppauso, @merlin-tc,

Can you apply this patch https://github.com/pluginsGLPI/tag/pull/207 and then force reinstallation of the plugin in CLI via : `bin/console plugin:install tag -f`
