### ISSUE TITLE
 Is it possible to add and list tags to tickets via API?

### ISSUE THREAD

**Issue by topcon-roberto-coutinho** [pluginsGLPI/tag#218]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0.16

### Plugin version

2.12.1

### Bug description

 Is it possible to add and list tags to tickets via API?
 
I searched the forum but didn't find anything that solved my problem.
I need to add and list tags to Tickets, Users and entities via API.

Is it possible? If so, which route and payload?

Is there documentation that addresses this?

**Comment by cconard96** [comment]
Yes. The itemtypes are PluginTagTagItem (/Ticket/2/PluginTagTagItem) and PluginTagTag (/PluginTagTag). If you need more help, feel free to make a new post on the forum as GitHub issues here should be reserved for bug reports.

A cleaner API integration is planned for new API coming with GLPI 11 (#139). The legacy API (the current one) will not be changed.
