### ISSUE TITLE
9.1.1 Impossible afficher sur différents profils

### ISSUE THREAD

**Issue by nicolas62** [pluginsGLPI/tag#24]
Bonjour,

L'affichage des TAGS fonctionne bien sur le profil Super-ADMIN mais impossible de les voir sur les autres profils.
Y'a t'il des droits à modifier pour que ça fonctionne ?
Est-ce un BUG ?

**Comment by nicolas62** [comment]
J'ai réussit à afficher les tags sur tous les profils en ajoutant les droits en lecture des catégories.
C'est un fonctionnement normal ?

**Comment by flegastelois** [comment]
Bonjour,
Le plugin se base sur les droits standard "Intitulés" du coeur de GLPI, c'est un comportement normal.
François
