### ISSUE TITLE
Plugins formulaire (formcreator) - pouvoir rajouter des tags

### ISSUE THREAD

**Issue by flegastelois** [pluginsGLPI/tag#3]
Hello,

Il faudrait pouvoir rajouter des tag dans les formulaires.

Voir si cela est plus une amélioration du plugin formcreator ou si c'est également sur le plugin tag.

++

**Comment by Manu1400** [comment]
L'ajout de tags dans les autres plugins est supporté (dont FormCreator). Utiliser si possible la version au dernier commit : https://github.com/pluginsGLPI/tag/commit/db2ca0f10df313a66bde67d6266b1f2c18ac5277
