### ISSUE TITLE
Permission to create tags

### ISSUE THREAD

**Issue by yurisilvano** [pluginsGLPI/tag#38]
I can establish which profiles can create tags? The only profile that can create tags is the super-admin?

**Comment by yurisilvano** [comment]
I already read https://github.com/pluginsGLPI/tag/issues/24
But i barely understand english... French not even translating. Is very difficult.
Plz, Explain me step by step, i am reeeeeally noob on GLPI.
Tks.

**Comment by trasher** [comment]
User says he can display tags on all profiles adding them write access to categories.

Use the forums if you need help on GLPI usage, keep bug tracker for bugs.
