### ISSUE TITLE
Associated item types with appliances

### ISSUE THREAD

**Issue by duylong** [pluginsGLPI/tag#40]
Hi,

Can not we associate the plugin "appliances" in the types of associated element? I can add tags for "appliances" if I do not add them to a list but I also see them in "Computers".

Is this normal behavior for this plugin?

**Comment by cedric-anne** [comment]
Hi,

The list of associated item types is hardcoded in the plugin. I just create a PR to add Appliance item type in the list. If approved, it will be available on next release.

**Comment by cedric-anne** [comment]
Done in https://github.com/pluginsGLPI/tag/pull/44.
