### ISSUE TITLE
Display of tags on ticket list 

### ISSUE THREAD

**Issue by tsmr** [pluginsGLPI/tag#5]
GLPI version 0.90.1
The tag column on the ticket list display no wanted characters :
![image](https://cloud.githubusercontent.com/assets/13178158/10844792/f9fa486e-7f02-11e5-9835-f7d72c7e1a82.png)

**Comment by Manu1400** [comment]
Fixed on https://github.com/pluginsGLPI/tag/commit/fc83b98f549302274f56aca655f5836e1b372548
