### ISSUE TITLE
GLPI 9.3 and Tag plugin, problem with solution button 

### ISSUE THREAD

**Issue by Corrano** [pluginsGLPI/tag#55]
Hello, after upgrade GLPI to 9.3 i found one important problem which is related with tag plugin (2.2.0).

When plugin is disabled, everything works fine.

![image](https://user-images.githubusercontent.com/7323944/42291549-a82a0128-7fcc-11e8-9772-e18a8d3ae25a.png)

But when plugin is enabled i can't solve any ticket and button **"Solution"** doesn't work. In debug mode i see this error.

![image](https://user-images.githubusercontent.com/39371670/42291640-4035dffa-7fcd-11e8-848a-d7554835a6c4.png)

If you have any idea what's wrong, I will be grateful for your help :)

**Comment by cedric-anne** [comment]
Hi,

Commit 66a7516f0ecb91455670484db4b93d5a803c2273 fixes this issue.

Regards
