### ISSUE TITLE
Can't login to GLPI when plugin installed

### ISSUE THREAD

**Issue by hgpit** [pluginsGLPI/tag#57]
Hi all,

Installed Tag Management plugin v2.1.2 onto our GLPI v9.2.3.

No user is able to login to GLPI. Login page just replies with:
"
Empty login or password

Log in again
"
 
We use LDAP to link our GLPI to Active Directory. If we disable/uninstall the plugin using a user is already logged in, it fixes the issue.

**Comment by cedric-anne** [comment]
Duplicates #39
