### ISSUE TITLE
Tags - can't remove

### ISSUE THREAD

**Issue by Pawel-FutureProcessing** [pluginsGLPI/tag#58]
Hello,
i have a problem with tags - after I add one of them - can't remove it - it is still show that tag in tag field.
_edit_
remembers last tag - that can't be deleted. I can change it to other one, but can't remove them.

**Comment by fabienfrima** [comment]
Hello,
I have the same problem since updating to GLPI 9.3.1. tests done with version 2.2.1 and 2.2.2 of the plugin.
Creating a new tag is also impossible.

**Comment by b-keller** [comment]
Hi,

same problem here.
GLPI 9.3.1
TAG 2.2.2

**Comment by mauriciolamego** [comment]
Good morning, I also appreciate a correction to the problem that is shown.
After you've inserted at least one tag, you can not remove all of them.
Thank you.

**Comment by b-keller** [comment]
Hi,
problem still here with GLPI 9.3.3
The only way to delete a tag is : mass action->remove tags

**Comment by cadegenn** [comment]
Hi,

Just saw I got the same problem.
GLPI 9.3.1
TAG 2.2.2

The correct title of this issue could be "Can't remove last tag on item edition page" because we can remove tags, only the last one remains. And as @b-keller suggest, there is a workaround.

Anyway, thank you for this useful plugin.

**Comment by RGiacometti** [comment]
Hello,

I have the same issue
GLPI 9.3.3
TAG 2.3.0

No error in php-errors.log & sql-errors.log

Thnaks

**Comment by cedric-anne** [comment]
Fixed by #76 .
