### ISSUE TITLE
[GLPI 9.4.1.1]+TAG 2.4.1 - can't set tag anymore

### ISSUE THREAD

**Issue by b-keller** [pluginsGLPI/tag#72]
Hi,

All is in the title, after upgrade GLPI to 9.4.1.1 and TAG plugin to 2.4.1(GLPI migration from 9.3.3 with tag plugin 2.2.2), I can't set tags on tickets or assets : list is empty and i see "No result found"... (root entity or other entities) I only can see tags that are previosly set.

does anyone have the same problem ?

Thx

**Comment by cedric-anne** [comment]
Fixed by #74.
