### ISSUE TITLE
php error in debug mode

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/tag#77]
Hello

I have this error on debug mode
glpi 9.4.2
PHP Warning: Invalid argument supplied for foreach() in C:\inetpub\wwwroot\plugins\tag\setup.php at line 89

**Comment by stonebuzz** [comment]
Seems identical to #81

**Comment by stonebuzz** [comment]
Hi @yalgva 
can you try this RP https://github.com/pluginsGLPI/tag/pull/89

Best regards

**Comment by yalgva** [comment]
thx fixed with 2.6
