### ISSUE TITLE
massive update of associated itemtypes fails

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/tag#78]
Unable to mass edit associated itemtypes on tags : the field does not show

![image](https://user-images.githubusercontent.com/14139801/60572531-16755200-9d76-11e9-89c2-bc996d5c8bc0.png)
 
[Wed Jul  3 09:34:49 2019] 127.0.0.1:45524 [200]: /ajax/dropdownMassiveAction.php
[Wed Jul  3 09:34:52 2019] PHP Fatal error:  Uncaught Error: Call to undefined method PluginTagTagItem::getItemtypes() in /var/www/html/glpi-94/plugins/tag/inc/tag.class.php:322
Stack trace:
#0 /var/www/html/glpi-94/inc/commondbtm.class.php(4795): PluginTagTag::getSpecificValueToSelect('type_menu', 'type_menu', Array, Array)
#1 /var/www/html/glpi-94/inc/massiveaction.class.php(881): CommonDBTM->getValueToSelect(Array, 'type_menu', Array, Array)
#2 /var/www/html/glpi-94/inc/massiveaction.class.php(620): MassiveAction::showMassiveActionsSubForm(Object(MassiveAction))
#3 /var/www/html/glpi-94/ajax/dropdownMassiveAction.php(48): MassiveAction->showSubForm()
#4 {main}
  thrown in /var/www/html/glpi-94/plugins/tag/inc/tag.class.php on line 322
[Wed Jul  3 09:34:52 2019] 127.0.0.1:45528 [500]: /ajax/dropdownMassiveAction.php - Uncaught Error: Call to undefined method PluginTagTagItem::getItemtypes() in /var/www/html/glpi-94/plugins/tag/inc/tag.class.php:322
Stack trace:
#0 /var/www/html/glpi-94/inc/commondbtm.class.php(4795): PluginTagTag::getSpecificValueToSelect('type_menu', 'type_menu', Array, Array)
#1 /var/www/html/glpi-94/inc/massiveaction.class.php(881): CommonDBTM->getValueToSelect(Array, 'type_menu', Array, Array)
#2 /var/www/html/glpi-94/inc/massiveaction.class.php(620): MassiveAction::showMassiveActionsSubForm(Object(MassiveAction))
#3 /var/www/html/glpi-94/ajax/dropdownMassiveAction.php(48): MassiveAction->showSubForm()
#4 {main}
  thrown in /var/www/html/glpi-94/plugins/tag/inc/tag.class.php on line 322

**Comment by stonebuzz** [comment]
Hi @btry 

at this step, the massive action form is for PluginTagTagItem object, is a CommonDBRelation and is not possible to update it.

This PR #86 prevent this by remove update action.

Best regards
