### ISSUE TITLE
PHP Warning(2): Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by jcervantes-sipecom** [pluginsGLPI/tag#81]
I have been receiving this emails every 5 minutes about 1 month ago until now:

Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659

 *** PHP Warning(2): Invalid argument supplied for foreach()
 Backtrace :
 plugins/tag/setup.php:90
 inc/plugin.class.php:168                           plugin_init_tag()
 inc/includes.php:104                               Plugin::load()
 front/cron.php:38                                  include()

I don't know how to stop it, and the reason for this problem.

**Comment by cedric-anne** [comment]
Hi,

Can you give us some details about your installation ?
GLPI version, plugin version, PHP version, ...

Regards

**Comment by jcervantes-sipecom** [comment]
Of course:

GLPI 9.4.3 Copyright (C) 2015-2019 Teclib' and contributors
FusionInventory 9.4+1.1 - Copyleft © 2010-2019 by FusionInventory Team

SO:
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

Aditional plugins:

Name | Directory | Version
Activities | activity | 2.5.0
File injection | datainjection | 2.7.0
Item's Lifecycle (uninstall) | uninstall | 2.6.2
Orders management | order | 2.5.2
Additionnal fields | fields | 1.10.1
Used items export | useditemsexport | 2.3.0
Reservation | reservation | 2.2.0
Behaviours | behaviors | 2.2.1
Print to pdf | pdf | 1.6.0
Form Validation | formvalidation | 0.6.3
Asset impacts | impacts | 1.3.2
Mask | mask | 2.3.0
Process Maker | processmaker | 3.6.5
Mail Analyzer | mailanalyzer | 1.6.1
Office Online | officeonline | 1.3.1
Archived eMail clean | cleanarchivedemails | 1.3.1
Ticket Cleaner | ticketcleaner | 2.5.1
Reports | reports | 1.13.1
Timeline of tickets | timelineticket | 9.4+1.0
IP Adressing | addressing | 2.8.0
OCS Inventory NG | ocsinventoryng | 1.6.0
FP Software | fpsoftware | 1.4.0
FP Consumables | fpconsumables | 1.3.0
Functional Areas | archifun | 2.1.0
Diagrams | archimap | 2.1.3
Dataflows | dataflows | 2.1.0
Apps structures | archisw | 2.1.3
Statecheck Rules | statecheck | 2.1.0
Notifications | notifications | 9.4+1.0
FusionInventory | fusioninventory | 9.4+1.1
Barcode | barcode | 2.4.0
Objects management | genericobject | 2.7.0
TaskDrop | taskdrop | 1.1.0
Costs | costs | 1.1.0
GDrive | gdrive | 1.2.0
ActualTime | actualtime | 1.2.0
GLPI Modifications | mod | 1.4.0
DPO Register | dporegister | 1.4
Dashboard | dashboard | 0.9.8
Tag Management | tag | 2.5.0
Credit vouchers | credit | 1.6.2
Form Creator | formcreator | 2.8.5
metabase | metabase | 1.0.0
Child ticket manager | childticketmanager | 2.1.3
More satisfaction | satisfaction | 1.4.3
Alerts | news | 1.5.4
Inventory number generation | geninventorynumber | 2.4.0
More Reporting | mreporting | 1.6.1
Escalation | escalade | 2.4.4
ItilCategory Groups | itilcategorygroups | 2.3.0
Accounts | accounts | 2.5.0
Others alerts | additionalalerts | 2.2.0
Suppliers imports | manufacturersimports | 2.2.0
Cartography | positions | 4.6.0
Printer counters | printercounters | 1.6.0
Human Resources | resources | 2.6.3
Environment | environment | 2.3.0
Dashboard access | mydashboard | 1.7.4
Financial reports | financialreports | 2.6.0
Typologies | typology | 2.6.0
Databases | databases | 2.2.1
Web applications | webapplications | 2.6.0
Domains | domains | 2.1.0
Shell Commands | shellcommands | 2.3.0
Entities portal | manageentities | 3.1.0
Consumable request | consumables | 1.5.0
Tasks list | tasklists | 1.5.0
Meta-Demands | metademands | 2.6.0
More ticket | moreticket | 1.5.1

**Comment by stonebuzz** [comment]
Hi @yalgva 
can you try this RP https://github.com/pluginsGLPI/tag/pull/89

Best regards

**Comment by jcervantes-sipecom** [comment]
> Hi @yalgva
> can you try this RP #89
> 
> Best regards

**Thanks, that was the solution.**

Although I honestly did not know how to apply it since you sent me only to one topic, there I did not know what to do, so I began to enter all the answers, until I found the part of the code to modify.

Isn't there a way to apply code changes faster?

**Comment by stonebuzz** [comment]
If you have no knowledge of patch file or git system, the better way is to change code manually, 

but for very long PR or patch it's very hard ^^
