### ISSUE TITLE
tag does not deleted or added in appliance plugin

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/tag#82]
Hello,
glpi 9.4.3
tag 2.5.0
appliance 2.5.0

I can't delete or add a tag on appliance plugin anymore

Could you help me please

Thank you

**Comment by stonebuzz** [comment]
Hi @yalgva 

can you try this PR https://github.com/pluginsGLPI/tag/pull/88

This PR fix your problem.

Best regards

**Comment by yalgva** [comment]
thx fixed with 2.6
