### ISSUE TITLE
Search criteria/arguments on Ticket

### ISSUE THREAD

**Issue by gabrielpetrone** [pluginsGLPI/tag#84]
TAG Version: 2.5.0
GLPI Version: 9.4.4
---
When i try to search in tickets with arguments:

> - Tag containing 'Estorno'
> AND
> - Tag containing 'Doc'
> AND
> - Assigned to Group is 'Suporte'

No results are found.
![tags-with-crteria-Suporte](https://user-images.githubusercontent.com/11214455/71422003-564e2f80-265d-11ea-8648-74df56aa3c1d.png)

If remove the 'assinged' criteria and keep only Plugin Tag, works fine:
![tags-without-criteria-Suporte](https://user-images.githubusercontent.com/11214455/71422004-564e2f80-265d-11ea-84ab-efc85048d7ff.png)

**Comment by gabrielpetrone** [comment]
Apparently this bug happens only if use the criteria 'Assigned'.
Today i tested with others arguments and worked fine:
![image](https://user-images.githubusercontent.com/11214455/72619041-2ff97800-391b-11ea-97d0-b2f62137a2b6.png)
For those dont speak portuguese, i'm using the search criterias:

>Tag containing 'entre'
>AND
>Tag containing 'Doc.'
>AND
>Create Date after -5 weeks
_i'm tried with 'Description containing {text}' and worked too! Not tested others criterias._

**Comment by stonebuzz** [comment]
Hi @gabrielpetrone 

can you test this PR -> https://github.com/pluginsGLPI/tag/pull/87

this PR refactor code concerning tickets search engine and allow to use 'is' operator much more easier for user.

best regards

**Comment by gabrielpetrone** [comment]
Almost done...
Now I can search with criteria:
>'TAGS' containing 
>AND 'GROUP' assigned
but still with troubles if uses more then one TAG condition:
![image](https://user-images.githubusercontent.com/11214455/73039387-91967680-3e34-11ea-95c4-530d159c783c.png)
_if uses TAGS is instead of containing, the issue still happening_

Examples that should be worked:
![image](https://user-images.githubusercontent.com/11214455/73039238-00270480-3e34-11ea-99f3-84c832537e03.png)
In this ticket I put 3 differents tags:
![image](https://user-images.githubusercontent.com/11214455/73039291-32386680-3e34-11ea-9c5f-ca0d877ddf50.png)

Anyway, thanks for your help!
