### ISSUE TITLE
problem on tag select

### ISSUE THREAD

**Issue by yalgva** [pluginsGLPI/tag#96]
tag 2.6.0 - glpi 9.4.3

hello
when I select tag in computer list, it displays off the tag on the item but continue to select the item in the list selection

example 
computer contains tag "a supprimer"
the aba... server contains two tag  "serveur" and "a supprimer"
But if i select computer does not contains a supprimer the result is the same but does not diplay "a supprimer"

![image](https://user-images.githubusercontent.com/30655170/77139125-138dcf00-6a75-11ea-9142-f025f7e0e927.png)

![image](https://user-images.githubusercontent.com/30655170/77139150-302a0700-6a75-11ea-980e-dd8032fc06f6.png)

**Comment by cedric-anne** [comment]
Hi,

Should be fixed by #107.

Regards
