### ISSUE TITLE
Tag Association with Webapplication plugin assets

### ISSUE THREAD

**Issue by b-keller** [pluginsGLPI/tag#99]
Hi,

I propose this code for create tag association only with web application :

in setup.php
` 
      // Plugin Webapplication
if ($plugin->isInstalled('webapplications') && $plugin->isActivated('webapplications')) {
         $CFG_GLPI['plugin_tag_itemtypes'][__('Assets')][] = 'PluginWebapplicationsWebapplication';
      }
`

It's working for my installation with GLPI 9.4.5 and tag 2.6.0

Thx

**Comment by stonebuzz** [comment]
Hi @b-keller 

thanks for contributing, can you open a pull request ?

Best regards

**Comment by b-keller** [comment]
Hi @stonebuzz 

It's done

Thx

**Comment by stonebuzz** [comment]
Link to #100

**Comment by cedric-anne** [comment]
Done in #100 (commit d2122bc42b1e4f41786c5d0cdb3240701244f0be).
